### PR TITLE
Update formula api

### PR DESCRIPTION
**Pull request by fpagnoux**
This was on mes-aides/embauche prod, but no PR has ever been issued to openfisca.
@MattiSG, this is your code. Maybe you remember ?

### CODE REVIEW

**Comment by MattiSG** [comment]
@fpagnoux Would you have the reference to the original commit?

**Comment by fpagnoux** [comment]
https://github.com/sgmap/openfisca-web-api/commit/d551972d8e4443aaaf9cec9d87f188936df98f52

**Comment by MattiSG** [comment]
I think this could date back from April and have been cherry-picked. No idea why this wasn't merged, nor if it has major impact.
I find the changeset to slightly improve readability by making functions more cohesive, but nothing critical.

**Comment by laem** [comment]
Cette PR a en fait un énorme impact sur la rapidité.

**Comment by laem** [comment]
See #46

**Pull request closed without merging**
