### PR TITLE
Improve /swagger resilience

### PR DESCRIPTION
**Pull request by MattiSG**
- Update output formula detection code (see openfisca/openfisca-core#329).
- Add integration test for /swagger.

I did test with all `master` branches, so I don't know if I should open the PR against `master` or `next`. Let me know if you want me to open against `next`.

### CODE REVIEW

**Comment by cbenz** [comment]
Merged into next.

By the way, I made some days ago a quick'n'dirty commit ce26bfd5ab6dcc72a919e96d7f2bdf0a914621d8 
Perhaps you could check if there's something interesting before I delete this branch (named exceptions)

**Comment by cbenz** [comment]
I let you test it then I'll merge into master

**Comment by MattiSG** [comment]
I found an issue in f5db628, closing for now, will reopen when fixed.

**Comment by MattiSG** [comment]
> I let you test it then I'll merge into master

Didn't get that. I did test with all other OpenFisca modules prior to opening this PR, it works fine, so for me it was already ok for merging into `master`  ;)  I guess the best is to discuss this IRL.

(the issue I found was only linked to the `/swagger` semantics, and this PR is an improvement over its current state in any case)

**Comment by MattiSG** [comment]
ce26bfd is good for dropping. I see only unfactorisation of CORS headers, for which I see no rationale. Please let me know if I'm doing anything wrong there  :)

**Comment by MattiSG** [comment]
So factorising CORS headers is a way to ensure calling the CORS-handling method is called at the very beginning of a controller, to avoid useless processing in case we're facing a [preflight request](http://www.w3.org/TR/cors/#simple-cross-origin-request-0).
It turns out that, after tests in different browsers, the given controllers are [simple requests](http://arunranga.com/examples/access-control/) for which there's no preflight, so there's no need to define headers first  :)

**Pull request closed without merging**
