### PR TITLE
Fix the condition to detect if the country package has decompositions.

### PR DESCRIPTION
**Pull request by fpagnoux**
Connected to #76.

Due to https://github.com/openfisca/openfisca-core/pull/397, any `TaxBenefitSystem` has a `DEFAULT_DECOMP_FILE` attribute.

We cannot use it to figure out whether a TBS has a real decomposition. We can instead check whether `DEFAULT_DECOMP_FILE` is not None, or if `DECOMP_DIR` exists.

### CODE REVIEW

**Comment by fpagnoux** [comment]
I don't know much about decompositions, and I'd prefer to learn about it 😄 . Can someone who use it tell me if this condition seem appropriate ?

**Comment by benjello** [comment]
It is ok for me. I started some work [here](https://github.com/openfisca/openfisca-core/commits/fix-decomposition) which I should finish soon if @cbenz gives me a hand ;-)

**Comment by cbenz** [comment]
This PR is now invalid since https://github.com/openfisca/openfisca-core/pull/450

**Comment by benjello** [comment]
So should we close this PR @cbenz  ?

**Comment by cbenz** [comment]
No, I must update it to follow openfisca/openfisca-core#450

**Pull request closed without merging**
