### PR TITLE
Change pastescript conda install instruction

### PR DESCRIPTION
**Pull request by laem**
The previous organisation is down

### CODE REVIEW

**Comment by cbenz** [comment]
Hmm sorry for this answer but since we stopped using Conda, I'd rather like to use pip in the Readme. I'm in a meeting but as quick as possible I would like to do the PR this way.

**Comment by laem** [comment]
OK for that, but only if everything works smoothly in pip (it does in conda) **AND** : 
- document the installation of pastescript to be able to run `paster serve --reload development-france.ini`
- rewrite the [-france doc](https://doc.openfisca.fr/en/install_for_development.html) to remove all conda references, it is very confusing at the moment, mixing conda and  `virtualenvwrapper`

**Comment by cbenz** [comment]
@laem I updated the PR. Does it seem OK for you?

I'm working on the regular doc

**Comment by cbenz** [comment]
OK, I updated the doc to remove any reference to Conda

**Comment by laem** [comment]
Looks good !

**Pull request merged**
