### PR TITLE
Run flake8 in make test

### PR DESCRIPTION
**Pull request by MattiSG**

### CODE REVIEW

**Comment by cbenz** [comment]
Merged after a small modification

**Comment by MattiSG** [comment]
Oh nice, we don't need the ugly workaround anymore?  :)
(re: 380b636309d06af0c5a915178eb6ec3573b9b59e)

**Comment by cbenz** [comment]
No! The "check syntax" make target was for code source with accepted flake8 errors, but not-accepted syntax errors :-) Web-API is flake8 errors free so "check syntax" is no more needed.

**Comment by MattiSG** [comment]
:dancer:

**Pull request closed without merging**
